swagger: '2.0'
info:
  version: 3.0.0
  title: Pol.is
  description: >-
    The Pol.is API for AI-powered conversations.
  termsOfService: 'https://pol.is/tos'
  contact:
    name: Pol.is API team
    email: foo@example.com
    url: 'https://pol.is'
  license:
    name: 'AGPL-3.0'
    url: 'https://opensource.org/licenses/AGPL-3.0'
host: polis-api-proxy.herokuapp.com
basePath: /api/v3
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: API key as user name. Password should be left blank.
paths:
  /conversations:
    post:
      security:
       - basicAuth: []
      description: Create a new conversation
      tags:
        - Conversations
      parameters:
        - name: topic
          in: formData
          default: ''
          type: string
        - name: description
          in: formData
          default: ''
          type: string
        - name: short_url
          in: formData
          default: false
          type: boolean
          description: will return an easily typeable shortlink
        - name: strict_moderation
          in: formData
          type: boolean
      responses:
        200:
          description: ''
          schema:
            type: object
            example:
              conversation_id: '1234abc'
              url: 'pol.is/1234abc'
            properties:
              conversation_id:
                type: string
                description: ''
              url:
                type: string
                description: ''
    get:
      security: []
      description: Get all the data for one conversation
      tags:
        - Conversations
      parameters:
        - name: conversation_id
          in: query
          type: string
          required: true
        - name: user_id
          in: query
          type: string
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/ConversationModel'
  /participants:
    get:
      security:
        - basicAuth: []
      description: Get all the data for conversation participants
      tags:
        - Participants
      parameters:
        - name: conversation_id
          in: query
          type: string
          required: true
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/ConversationParticipants'
  /votes:
    post:
      security:
        - basicAuth: []
      description: Submit vote data.
      tags:
        - Votes
      parameters:
        - name: body
          in: body
          description: Vote object that needs to be added.
          required: true
          schema:
            $ref: '#/definitions/VoteModel'
      responses:
        200:
          description: ''
          schema:
            type: object
            properties:
              currentPid:
                type: integer
  /math/pca2:
    get:
      tags:
        - Math
      parameters:
        - name: conversation_id
          in: query
          type: string
          required: true
        - name: lastVoteTimestamp
          in: query
          type: integer
          format: int64
          description: Milliseconds since Unix epoch.
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/PCA2Response'
  /comments:
    get:
      tags:
        - Comments
      responses:
        default:
          description: ''
  /ptptStats:
    get:
      tags:
        - Stats
      parameters:
        - name: conversation_id
          in: query
          type: string
          required: true
      responses:
        200:
          description: ''
          schema:
            type: object
            properties:
              _id:
                type: string
              zid:
                description: Conversation ID
                type: integer
              lastVoteTimestamp:
                type: integer
                format: int64
                description: Timestamp of last vote in conversation. Milliseconds since Unix epoch.
              ptptstats:
                $ref: '#/definitions/PTPTStatsVectors'
            example:
              _id: 583fe36e7d5d2ee98915160e
              zid: 15169
              lastVoteTimestamp: 1480582081755
              ptptstats:
                pid: [9, 10, 11]
                gid: [0, 0, 1]
                n-votes: [21, 27, 27]
                centricness: [-0.5159909872007928, -1.3150581183585088, 0.3327595737808212]
                coreness: [-0.11622667139125253, 0.3186507192911382, 0.2658691164608967]
                extremeness: [-0.18028159265559968, 1.071078390338353, -0.9979297374105403]
definitions:
  VoteModel:
    type: object
    description: A vote object
    properties:
      agid:
        type: integer
      conversation_id:
        type: string
      pid: {}
      tid:
        type: integer
      vote:
        type: integer
        enum: [-1, 0, 1]
  PCA2Response:
    type: object
    description: ''
    properties:
      _id:
        type: string
        description: ''
      base-clusters:
        type: object
        description: ''
      consensus:
        type: object
        description: ''
      group-clusters:
        type: array
        items:
          type: object
      group-votes:
        type: object
        description: ''
      in-conv:
        type: array
        items:
          type: integer
      lastModTimestamp:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      lastVoteTimestamp:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      n:
        type: integer
        description: ''
      n-cmts:
        type: integer
        description: ''
      pca:
        type: object
        description: ''
      repness:
        type: object
        description: ''
      user-vote-counts:
        type: array
        items:
          type: array
          items:
            type: integer
      votes-base:
        type: object
        description: ''
  PTPTStatsVectors:
    type: object
    description: Data vectors. (Think of them as columns.)
    properties:
      pid:
        type: array
        items:
          description: Participant ID
          type: integer
      gid:
        type: array
        items:
          description: Group ID
          type: integer
      n-votes:
        type: array
        items:
          description: Count of votes cast by the participant
          type: integer
      centricness:
        type: array
        items:
          description: >-
            Metric representing how "central" a participant's views are in scope of CONVERSATION. Higher numbers are more centric.
          type: number
          format: float
          maximum: 1
      coreness:
        type: array
        items:
          description: >-
            Metric representing how "central" a participant's views are in scope of GROUP. Higher numbers are more centric.
          type: number
          format: float
          maximum: 1
      extremeness:
        type: array
        items:
          description: >-
            Metric representing how extreme a participant's views are in scope of GROUP. (This is to say, these participants are the furthest away from the center of the conversation in the direction of the group in question, and therefore represent the most extreme version of the views of a given group; these are the ideologues.) Max value is undefined, but probably less than 2.
          type: number
          format: float
  ConversationModel:
    type: object
    properties:
      topic:
        type: string
        description: 'Conversation title.'
      description:
        type: string
        description: >-
          Conversation description shown above interactive portion. May contain
          markdown formatting.
      is_anon:
        type: boolean
      is_active:
        type: boolean
      is_public:
        type: boolean
      email_domain:
        type: string
        x-nullable: true
      owner:
        type: integer
      participant_count:
        type: integer
      created:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      strict_moderation:
        type: boolean
      profanity_filter:
        type: boolean
      spam_filter:
        type: boolean
      context:
        x-nullable: true
      modified:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      owner_sees_participation_stats:
        type: boolean
      course_id:
        x-nullable: true
      lti_users_only:
        type: boolean
      link_url:
        type: string
        x-nullable: true
      upvotes:
        type: integer
      parent_url:
        type: string
        x-nullable: true
      vis_type:
        type: integer
      write_type:
        type: integer
      bgcolor:
        type: string
        x-nullable: true
      help_type:
        type: integer
      socialbtn_type:
        type: integer
      style_btn:
        x-nullable: true
      auth_needed_to_vote:
        type: boolean
      auth_needed_to_write:
        type: boolean
      auth_opt_fb:
        type: boolean
      auth_opt_tw:
        type: boolean
      auth_opt_allow_3rdparty:
        type: boolean
      help_bgcolor:
        x-nullable: true
      help_color:
        x-nullable: true
      is_data_open:
        type: boolean
      is_slack:
        type: boolean
      site_id:
        type: string
      auth_opt_fb_computed:
        type: boolean
      auth_opt_tw_computed:
        type: boolean
      ownername:
        type: string
      is_mod:
        type: boolean
      is_owner:
        type: boolean
      pp:
        type: boolean
      conversation_id:
        type: string
  ConversationParticipants:
    type: object
    properties:
      created:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      last_interaction:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      last_notified:
        type: integer
        format: int64
        description: Milliseconds since Unix epoch.
      mod:
        type: integer
      pid:
        description: Participant ID within this conversation context. Often corresponds to index in vectors.
        type: integer
      subscribed:
        type: integer
      uid:
        type: integer
      vote_count:
        type: integer
      zid:
        description: Conversation ID
        type: integer
